# Generated by Django 5.0.2 on 2024-02-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_accountinfo_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='account_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.account'),
        ),
    ]
